import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "@/components/SessionProvider";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// Fonction (et non `metadata` statique) pour être évaluée à chaque requête :
// APP_ENV vient des vars Cloudflare, injectées dans process.env par OpenNext
// au démarrage du Worker, pas au moment du build.
export function generateMetadata(): Metadata {
	const isDev = process.env.APP_ENV === "dev";

	return {
		description: "Generated by create next app",
		title: isDev ? "ParcCours DEV" : "ParcCours",
		manifest: isDev ? "/manifest-dev.json" : "/manifest.json",
	};
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SessionProvider>{children}</SessionProvider>
			</body>
		</html>
	);
}
